import type { Metadata } from "next";
import localFont from "next/font/local";

import { QueryProvider } from "@/shared/providers/query-client-provider";
import "./globals.css";
import { Toaster } from "@moum-zip/ui/components";
import { NavigationMenu } from "@/shared/ui/navigation-menu";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className} ${pretendard.variable} antialiased`}>
        <QueryProvider>
          <NavigationMenu />
          <main>{children}</main>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
