import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AmplitudeInit } from "@/amplitude";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className} ${pretendard.variable} bg-background-secondary antialiased`}>
        <AmplitudeInit />
        {children}
      </body>
    </html>
  );
}
