import type { Metadata } from "next";
import "./globals.css";
import { AmplitudeInit } from "@/amplitude";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link rel="preconnect" href="https://cdn.jsdelivr.net" crossOrigin="" />
        <link
          rel="stylesheet"
          crossOrigin=""
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css"
        />
        <script src="https://accounts.google.com/gsi/client" async />
      </head>
      <body className="bg-background-secondary antialiased">
        <AmplitudeInit />
        {children}
      </body>
    </html>
  );
}
