import type { SpaceInfo } from "@/entities/space/model/types";

export const MOCK_SPACE: SpaceInfo[] = [
  {
    id: "1",
    name: "스페이스 1",
    status: "ongoing",
    currentParticipants: 20,
    thumbnailUrl: "",
    maxParticipants: 20,
    startDate: "2021년 11월 17일",
    category: "study",
    color: "#00bd7e",
    location: "서울 강남구",
  },
  {
    id: "2",
    name: "스페이스 2",
    status: "archived",
    currentParticipants: 20,
    maxParticipants: 20,
    startDate: "2021년 11월 17일",
    endDate: "2022년 4월 17일",
    category: "study",
    color: "#e2a2e2",
    location: null,
  },
  {
    id: "3",
    name: "모임 Title",
    status: "archived",
    currentParticipants: 20,
    maxParticipants: 20,
    startDate: "2021년 11월 17일",
    endDate: "2022년 4월 17일",
    category: "project",
    color: "#e2e2e2",
    location: "서울 강남구",
  },
  {
    id: "4",
    name: "스페이스 4",
    status: "ongoing",
    currentParticipants: 20,
    maxParticipants: 20,
    startDate: "2021년 11월 17일",
    category: "study",
    color: "#e2e2e2",
    location: null,
  },
];
