export const ERROR_CODES = {
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  NOT_FOUND: "NOT_FOUND",
  POST_NOT_FOUND: "POST_NOT_FOUND",
  REQUEST_FAILED: "REQUEST_FAILED",
  SPACE_ACCESS_DENIED: "SPACE_ACCESS_DENIED",
  SPACE_NOT_FOUND: "SPACE_NOT_FOUND",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
