name: development deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  test-and-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm biome check .

      # 2. 타입 체크 및 테스트 (변경된 패키지만!)
      - name: Type Check & Test
        run: pnpm turbo check-types test --filter=...[origin/dev]

      # 3. 빌드 (변경된 패키지만!)
      - name: Build
        run: pnpm turbo build --filter=...[origin/dev]

      - name: install vercel cli
        run: pnpm add --global vercel@latest

      - name: Vercel 환경 정보 가져오기
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Production (실제 서비스) 환경용으로 빌드 
      - name: 프로젝트 빌드
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Production (실제 서비스) 도메인으로 배포
      - name: Vercel에 프로젝트 배포
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
